name: fimber
description: Extensible logging for Flutter - based on Timber on Android, using similar (as far as Dart lang allows) method API with same concepts for tree and planting logging tree.
version: 0.6.6
homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dev_dependencies:
  lint: ^2.0.0
  test: ^1.0.0
