name: flutter_fimber
description: Flutter extension for Fimber logging API, it will use native OS Logging statements via channel.
version: 0.6.5
homepage: https://github.com/magillus/flutter-fimber
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.0.0'

dependencies:
  fimber:
    git:
      url: https://github.com/swaglive/flutter-fimber.git
      path: fimber
      ref: 0.6.5-hotfix.11
  flutter:
    sdk: flutter

dev_dependencies:
  test: '^1.16.5'
  pedantic: '^1.11.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.magillus.flutterfimber
        pluginClass: FlutterFimberPlugin
      ios:
        pluginClass: FlutterFimberPlugin
