name: flutter_fimber
description: Flutter extension for Fimber logging API, it will use native OS Logging statements via channel.
version: 0.7.0
homepage: https://github.com/magillus/flutter-fimber
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: '>=2.0.0'

dependencies:
  plugin_platform_interface: ^2.1.4
  flutter:
    sdk: flutter
  fimber:
    git:
      url: https://github.com/swaglive/flutter-fimber.git
      path: fimber
      ref: 0.7.0-hotfix.2

dev_dependencies:
  test: '^1.24.1'
  flutter_lints: '^2.0.0'
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.magillus.flutter_fimber
        pluginClass: FlutterFimberPlugin
        sharedDarwinSource: true
      ios:
        pluginClass: FlutterFimberPlugin
        sharedDarwinSource: true
