name: fimber_io
description: Version of Fimber package with support for File based loggers - dependent on dart::io
version: 0.6.6
publish_to: none

homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fimber:
    git:
      url: https://github.com/swaglive/flutter-fimber.git
      path: fimber
      ref: 0.6.5-hotfix.4
  synchronized: ^3.0.0+2
  intl: ^0.17.0

dev_dependencies:
  test: '^1.16.5'
  pedantic: '^1.11.0'
  flutter_lints: ^1.0.4
