name: fimber_io
description: Version of Fimber package with support for File based loggers - dependent on dart::io
version: 0.7.0
publish_to: none

homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  fimber:
    git:
      url: https://github.com/swaglive/flutter-fimber.git
      path: fimber
      ref: 0.7.0-hotfix.3
  intl: '>=0.18.0 <0.20.0'
  synchronized: ^3.0.0

dev_dependencies:
  lint: ^2.0.0
  test: ^1.0.0
